/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wlaMWWD6Fda
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Button } from "@/components/ui/button"

export function StarRating({ starCount, title, }: any) {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center gap-2">
          <Label htmlFor="rating">Your rating:</Label>
          <RadioGroup aria-label="Rating" id="rating" className="flex items-center gap-2">
            {[...Array(starCount)].map((_, index) => {
              const ratingValue = starCount - index;
              return (
                  <>
                    <RadioGroupItem value={ratingValue.toString()} id={`rating-${ratingValue}`} className="peer sr-only" key={ratingValue} />
                    <Label htmlFor={`rating-${ratingValue}`} className="cursor-pointer" title={`${ratingValue} stars`}>
                      <StarIcon className="h-6 w-6 fill-primary" />
                    </Label>
                  </>
              );
            })}
          </RadioGroup>
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        {/*<Button type="submit">Submit</Button>*/}
      </CardFooter>
    </Card>
  )
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
